validates:
  user:
    maximum_name: 50
    maximum_email: 255
    minimum_pass: 6
  location_type:
    maximum_name: 50
  service:
    maximum_name: 50
  bed_detail:
    maximum_name: 50

search_fields:
  user: ["name", "email", "created_at", "updated_at"]
  location_type: ["name", "created_at", "updated_at"]
  room: ["name", "occupancy_limit", "living_room", "bed_room", "bath_room",
    "number_of_bed", "quantity", "price", "created_at", "updated_at"]
  location: ["name", "national", "zip_code", "description", "status",
    "location_type_id", "user_id", "created_at", "updated_at"]
  service: ["name", "created_at", "updated_at"]
  bed_detail: ["name", "created_at", "updated_at"]

controllers:
  admin:
    users:
      pag: 10
    location_types:
      pag: 10
    services:
      pag: 10
    bed_details:
      pag: 10
    locations:
      page: 5

  manager:
    rooms:
      page: 5
    locations:
      page: 5

manager:
  rooms:
    index:
      page: 5

reviews:
  form:
    row_numbers: 3
